config/routes.rb
Rails.application.routes.draw do
  get 'ask', to: 'questions#ask', as: :ask
  get 'answer', to: 'questions#answer', as: :answer
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def ask
  end

  def answer
    # @answer = params[:answer
    @ask = params[:questions]
    # raise
    if @ask.end_with?('?')
      @answer = 'Silly question, get dressed and go to work!'
    elsif @ask == 'i am going to work'
      @answer = 'Great'
    else
      @answer = "I don't care, get dressed and go to work!"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_controller_helper.rb
module QuestionsControllerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/answer.html.erb
<h1> Stupid Coaching</h1>
<p><%= @ask %></p>
<p><%= @answer %></p>
<%= link_to("Ask a new question", answer_path, { target: "_blank"}) %>

app/views/questions/ask.html.erb
<!-- <form action="/@ask" method="get">
  <input type="text" name="your_question" placeholder="I am going to work">
  <input type="submit">
</form> -->
<h1> Stupid Coaching</h1>
<form action="/answer">
  <input type="text" name="questions">
  <input type="submit" value="Ask!">
</form>